/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as BooksOnLoanRouteImport } from './routes/books-on-loan'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksOnLoanRoute = BooksOnLoanRouteImport.update({
  id: '/books-on-loan',
  path: '/books-on-loan',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/books': typeof BooksRoute
  '/books-on-loan': typeof BooksOnLoanRoute
  '/classes': typeof ClassesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/books': typeof BooksRoute
  '/books-on-loan': typeof BooksOnLoanRoute
  '/classes': typeof ClassesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/books': typeof BooksRoute
  '/books-on-loan': typeof BooksOnLoanRoute
  '/classes': typeof ClassesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/books'
    | '/books-on-loan'
    | '/classes'
    | '/reset-password'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/books'
    | '/books-on-loan'
    | '/classes'
    | '/reset-password'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/books'
    | '/books-on-loan'
    | '/classes'
    | '/reset-password'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  BooksRoute: typeof BooksRoute
  BooksOnLoanRoute: typeof BooksOnLoanRoute
  ClassesRoute: typeof ClassesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books-on-loan': {
      id: '/books-on-loan'
      path: '/books-on-loan'
      fullPath: '/books-on-loan'
      preLoaderRoute: typeof BooksOnLoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  BooksRoute: BooksRoute,
  BooksOnLoanRoute: BooksOnLoanRoute,
  ClassesRoute: ClassesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
